import AppKit

/// In-memory clipboard history (text only). Nothing is written to disk, and
/// items flagged as concealed/transient by password managers are skipped.
@MainActor
final class ClipboardStore: ObservableObject {
    struct Entry: Identifiable, Equatable {
        let id = UUID()
        let text: String
        var pinned = false
    }

    @Published private(set) var entries: [Entry] = []
    @Published var paused = false

    private let limit = 40
    private let maxLength = 5_000
    private var lastChangeCount = NSPasteboard.general.changeCount
    private var timer: Timer?

    private let ignoredTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword"
    ]

    func start() {
        timer = Timer.scheduledTimer(withTimeInterval: 0.6, repeats: true) { [weak self] _ in
            Task { @MainActor in self?.poll() }
        }
    }

    /// Pinned entries first, then newest first.
    var sorted: [Entry] {
        entries.filter(\.pinned) + entries.filter { !$0.pinned }
    }

    private func poll() {
        let pasteboard = NSPasteboard.general
        guard pasteboard.changeCount != lastChangeCount else { return }
        lastChangeCount = pasteboard.changeCount
        guard !paused else { return }

        let types = (pasteboard.types ?? []).map(\.rawValue)
        if types.contains(where: { ignoredTypes.contains($0) }) { return }

        guard let raw = pasteboard.string(forType: .string) else { return }
        let text = String(raw.trimmingCharacters(in: .whitespacesAndNewlines).prefix(maxLength))
        guard !text.isEmpty else { return }
        insert(text)
        ActivityStore.shared.record()
    }

    private func insert(_ text: String) {
        var pinned = false
        if let existing = entries.firstIndex(where: { $0.text == text }) {
            pinned = entries[existing].pinned
            entries.remove(at: existing)
        }
        entries.insert(Entry(text: text, pinned: pinned), at: 0)

        // Trim oldest unpinned entries beyond the limit.
        while entries.count > limit, let idx = entries.lastIndex(where: { !$0.pinned }) {
            entries.remove(at: idx)
        }
    }

    /// Put an entry back on the system clipboard.
    func copy(_ entry: Entry) {
        let pasteboard = NSPasteboard.general
        pasteboard.clearContents()
        pasteboard.setString(entry.text, forType: .string)
        lastChangeCount = pasteboard.changeCount   // don't re-capture our own write
    }

    func togglePin(_ entry: Entry) {
        guard let idx = entries.firstIndex(of: entry) else { return }
        entries[idx].pinned.toggle()
    }

    func remove(_ entry: Entry) {
        entries.removeAll { $0.id == entry.id }
    }

    func clearUnpinned() {
        entries.removeAll { !$0.pinned }
    }
}
